language: node_js
node_js:
  - "8"
before_script:
  - psql -c "CREATE DATABASE tznvnvbe;" -U postgres
  - psql -c "CREATE USER tznvnvbe WITH PASSWORD 'f9PLh5CImii-y6vaTwevSAKSh50pRi06';" -U postgres
after_success:
- npm run coverage